version: 1.0.{build}

environment:
  nodejs_version: "6.5.0"
  # TODO: test cassandra with docker on travis
  # While that is not configured we do not
  # run automated test for cassandra client
  CASSANDRA_PORT: tcp://localhost:9042
  DB_CLIENTS: mysql,postgresql,sqlserver,sqlite
  # postgres
  POSTGRES_PORT: tcp://localhost:5432
  POSTGRES_ENV_POSTGRES_USER: postgres
  POSTGRES_ENV_POSTGRES_PASSWORD: Password12!
  POSTGRES_ENV_POSTGRES_DB: sqlectron
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.4
  PGUSER: postgres
  PGPASSWORD: Password12!
  # mysql
  MYSQL_PORT: tcp://localhost:3306
  MYSQL_ENV_MYSQL_USER: root
  MYSQL_ENV_MYSQL_PASSWORD: Password12!
  MYSQL_ENV_MYSQL_DATABASE: sqlectron
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  MYSQL_PWD: Password12!
  # sql server
  SQLSERVER_ENV_SQLSERVER_HOST: localhost
  SQLSERVER_ENV_SQLSERVER_PORT: 1433
  SQLSERVER_ENV_SQLSERVER_USER: sa
  SQLSERVER_ENV_SQLSERVER_PASSWORD: Password12!
  SQLSERVER_ENV_SQLSERVER_DATABASE: sqlectron

services:
  - mysql
  - postgresql94
  - mssql2008r2sp2

init:
  - ps: Install-Product node $env:nodejs_version
  - npm -v
  - node -v
  - npm cache clean
  - SET PATH=%POSTGRES_PATH%\bin;%MYSQL_PATH%\bin;%PATH%

test: false

install:
  - npm install

build_script:
  # postgres
  - createdb sqlectron
  - psql -d sqlectron -a -f spec/databases/postgresql/schema/schema.sql
  # mysql
  - mysql -e "create database sqlectron;" --user=root
  - mysql sqlectron < spec/databases/mysql/schema/schema.sql --user=root
  # sqlserver
  - ps: ./appveyor-sqlserver.ps1 SQL2008R2SP2
  - sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE sqlectron" -d "master"
  - sqlcmd -S localhost,1433 -U sa -P Password12! -i spec/databases/sqlserver/schema/schema.sql -d "sqlectron"
  - sqlcmd -S localhost,1433 -U sa -P Password12! -Q "select table_name from information_schema.tables" -d "sqlectron"
  - npm test
